# Generated by Django 4.0.6 on 2022-10-31 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followers',
            old_name='followers',
            new_name='whoFollow',
        ),
    ]
